apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app.kubernetes.io/component: object-store
spec:
  serviceName: {{ .Release.Name }}-minio
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          command:
            - minio
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.consolePort }}"
          ports:
            - containerPort: {{ .Values.minio.apiPort }}
            - containerPort: {{ .Values.minio.consolePort }}
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.credentials.accessKey }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.credentials.secretKey }}
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.minio.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.apiPort }}
      targetPort: {{ .Values.minio.apiPort }}
      name: api
    - port: {{ .Values.minio.consolePort }}
      targetPort: {{ .Values.minio.consolePort }}
      name: console
  selector:
    app: minio
