apiVersion: v1
kind: Service
metadata:
  name: {{ include "pocket-advisor-app.name" . }}
  labels:
    {{- include "pocket-advisor-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 443
      targetPort: https
